/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

/**
 *
 * @author Korisnik
 */
public class DetaljiKupcaForma extends javax.swing.JFrame {

    /**
     * Creates new form DetaljiKupcaForma
     */
    public DetaljiKupcaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIme = new javax.swing.JLabel();
        jLabelPrezime = new javax.swing.JLabel();
        jLabelBrojLK = new javax.swing.JLabel();
        jLabelKontakt = new javax.swing.JLabel();
        jLabelDatumRodjenja = new javax.swing.JLabel();
        jLabelMesto = new javax.swing.JLabel();
        jButtonZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelIme.setText("Ime: ");

        jLabelPrezime.setText("Prezime: ");

        jLabelBrojLK.setText("Broj LK: ");

        jLabelKontakt.setText("Kontakt:");

        jLabelDatumRodjenja.setText("Datum rodjenja: ");

        jLabelMesto.setText("Mesto");

        jButtonZatvori.setText("Zatvori");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonZatvori)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBrojLK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelKontakt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDatumRodjenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelIme)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrezime)
                .addGap(18, 18, 18)
                .addComponent(jLabelBrojLK)
                .addGap(18, 18, 18)
                .addComponent(jLabelKontakt)
                .addGap(18, 18, 18)
                .addComponent(jLabelDatumRodjenja)
                .addGap(18, 18, 18)
                .addComponent(jLabelMesto)
                .addGap(18, 18, 18)
                .addComponent(jButtonZatvori)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void popuniPodatke(domen.Kupac k) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy");
        jLabelIme.setText("Ime: " + k.getIme());
        jLabelPrezime.setText("Prezime: " + k.getPrezime());
        jLabelBrojLK.setText("Broj Loyalty Kartice: " + (k.getBrojLoyaltyKartice() == null ? "-" : k.getBrojLoyaltyKartice()));
        jLabelKontakt.setText("Kontakt: " + k.getKontakt());
        jLabelDatumRodjenja.setText("Datum rođenja: " + (k.getDatumRodjenja() == null ? "-" : sdf.format(k.getDatumRodjenja())));
        jLabelMesto.setText("Mesto: " + (k.getMesto() == null ? "-" : k.getMesto().getNaziv()));
    }

    public void zatvoriAddActionListener(java.awt.event.ActionListener actionListener) {
        jButtonZatvori.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JLabel jLabelBrojLK;
    private javax.swing.JLabel jLabelDatumRodjenja;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelKontakt;
    private javax.swing.JLabel jLabelMesto;
    private javax.swing.JLabel jLabelPrezime;
    // End of variables declaration//GEN-END:variables
}
