/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

/**
 *
 * @author Korisnik
 */
public class DetaljiRacunaForma extends javax.swing.JFrame {

    /**
     * Creates new form DetaljiRacunaForma
     */
    public DetaljiRacunaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelKupac = new javax.swing.JLabel();
        jLabelProdavac = new javax.swing.JLabel();
        jLabelDatumIzdavanja = new javax.swing.JLabel();
        jLabelNacinPlacanja = new javax.swing.JLabel();
        jLabelNapomena = new javax.swing.JLabel();
        jLabelUkupanIznos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jButtonZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelKupac.setText("Kupac");

        jLabelProdavac.setText("Prodavac:");

        jLabelDatumIzdavanja.setText("Datum izdavanja: ");

        jLabelNacinPlacanja.setText("Način plaćanja: ");

        jLabelNapomena.setText("Napomena: ");

        jLabelUkupanIznos.setText("Ukupan iznos: ");

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavke);

        jButtonZatvori.setText("Zatvori");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                            .addComponent(jLabelNapomena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelDatumIzdavanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelProdavac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNacinPlacanja, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKupac)
                    .addComponent(jLabelProdavac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatumIzdavanja)
                    .addComponent(jLabelNacinPlacanja))
                .addGap(18, 18, 18)
                .addComponent(jLabelNapomena)
                .addGap(18, 18, 18)
                .addComponent(jLabelUkupanIznos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonZatvori)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void popuniPodatke(domen.Racun r) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd.MM.yyyy.");
        jLabelDatumIzdavanja.setText("Datum izdavanja: " + (r.getDatumIzdavanja() == null ? "-" : sdf.format(r.getDatumIzdavanja())));
        jLabelKupac.setText("Kupac: " + r.getKupac().getIme() + " " + r.getKupac().getPrezime());
        jLabelProdavac.setText("Prodavac: " + r.getProdavac().getIme() + " " + r.getProdavac().getPrezime());
        jLabelNacinPlacanja.setText("Način plaćanja: " + r.getNacinPlacanja());
        jLabelNapomena.setText("Napomena: " + (r.getNapomena() == null || r.getNapomena().isEmpty() ? "-" : r.getNapomena()));
        jLabelUkupanIznos.setText("Ukupan iznos: " + String.format("%.2f", r.getUkupanIznos()));

        forme.model.ModelTabeleStavki mts = new forme.model.ModelTabeleStavki(r.getStavke());
        jTableStavke.setModel(mts);
    }

    public void zatvoriAddActionListener(java.awt.event.ActionListener actionListener) {
        jButtonZatvori.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JLabel jLabelDatumIzdavanja;
    private javax.swing.JLabel jLabelKupac;
    private javax.swing.JLabel jLabelNacinPlacanja;
    private javax.swing.JLabel jLabelNapomena;
    private javax.swing.JLabel jLabelProdavac;
    private javax.swing.JLabel jLabelUkupanIznos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavke;
    // End of variables declaration//GEN-END:variables
}
